In [1]:
from __future__ import print_function,division,absolute_import

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [2]:
x=np.random.randint(1,8,20)
y=np.array([(50*i+50)/100 for i in x])

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=123)


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential([])
model.add(Dense(1,input_dim=1))



In [5]:
model.compile(optimizer='sgd',loss='mean_squared_error',metrics=['accuracy','MAE'])

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(x_train,y_train,epochs=50)

Train on 14 samples
Epoch 1/50
14/14 [==============================] - 0s 26ms/sample - loss: 1.5974 - accuracy: 0.0714 - MAE: 1.1242
Epoch 2/50
14/14 [==============================] - 0s 156us/sample - loss: 0.3617 - accuracy: 0.0714 - MAE: 0.5247
Epoch 3/50
14/14 [==============================] - 0s 301us/sample - loss: 0.1053 - accuracy: 0.0714 - MAE: 0.2881
Epoch 4/50
14/14 [==============================] - 0s 209us/sample - loss: 0.0520 - accuracy: 0.0714 - MAE: 0.2002
Epoch 5/50
14/14 [==============================] - 0s 293us/sample - loss: 0.0407 - accuracy: 0.0714 - MAE: 0.1638
Epoch 6/50
14/14 [==============================] - 0s 282us/sample - loss: 0.0383 - accuracy: 0.0714 - MAE: 0.1569
Epoch 7/50
14/14 [==============================] - 0s 387us/sample - loss: 0.0376 - accuracy: 0.0714 - MAE: 0.1546
Epoch 8/50
14/14 [==============================] - 0s 573us/sample - loss: 0.0373 - accuracy: 0.0714 - MAE: 0.1534
Epoch 9/50
14/14 [==============================] - 0

In [8]:
model.predict([9])

array([[5.3070183]], dtype=float32)

In [9]:
x_train

array([5, 4, 3, 6, 7, 5, 1, 7, 3, 5, 6, 7, 2, 6])

In [10]:
y_train

array([3. , 2.5, 2. , 3.5, 4. , 3. , 1. , 4. , 2. , 3. , 3.5, 4. , 1.5,
       3.5])